name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
      - name: Check Out Repo 
        uses: actions/checkout@v2
      
      - name: Read Dockerfile content
        id: dockerfile
        uses: juliangruber/read-file-action@v1
        with:
          path: ./Dockerfile
          
      - name: Extract docker tag
        id: dockertag
        uses: tmelliottjr/extract-regex-action@v1.4.0
        with:
          regex: ':(.*)'
          flags: "gm"
          input: ${{ steps.dockerfile.outputs.content }}
      
      - name: Echo test
        run: echo "${{ steps.dockertag.outputs.resultString }}"
      
      #- name: Login to Docker Hub
      #  uses: docker/login-action@v1
      #  with:
      #    username: ${{ secrets.DOCKER_HUB_USERNAME }}
      #    password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      #- name: Set up Docker Buildx
      #  id: buildx
      #  uses: docker/setup-buildx-action@v1

      #- name: Build and push
      #  id: docker_build
      #  uses: docker/build-push-action@v2
      #  with:
      #    context: ./
      #    file: ./Dockerfile
      #    push: true
      #    tags: ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:latest, ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:${{ steps.read_version.outputs.version }}, ${{ secrets.DOCKER_HUB_USERNAME }}/matse_calendar_frontend:${{ github.sha }}

      #- name: Image digest
      #  run: echo ${{ steps.docker_build.outputs.digest }}
